class A { 
	method m1(a) { return a + 1 }
}

test "Test message not understood case sensitive" {

	const a = new A()
				
	try {
		a.M1(3)
		assert.fail("Should have thrown message not understood")
	}	
	catch e : MessageNotUnderstoodException {
		// ok !
	}

}