import wollok.lang.Exception

class MyException inherits Exception {}
class A {
	method m1() {
	}
}
test "Test Then Always excecuted even without an exception raised" {

	const a = new A()
	var counter = 0

	try {
		a.m1()
		counter = counter + 1
	}
	catch e : MyException
		console.println("Exception raised!") // OK!
	then always
		counter = counter + 1 

	assert.equals(2, counter)

}