import wollok.lang.Exception

class MyException inherits Exception {}
class A { method m1() { throw new MyException() } }

test "Test then always excecuted on exception" {

	const a = new A()
	var counter = 0
	
	try {
		a.m1()
	}

	catch e : MyException
		console.println("Exception raised!") // OK!
	
	then always
			counter = counter + 1

	assert.equals(1, counter)

}