import wollok.lang.Exception

class AException inherits Exception {  constructor(m) = super(m) }
class BException inherits AException {  constructor(m) = super(m) }
class CException inherits Exception {  constructor(m) = super(m) }
			
class A { 
	method m1() { throw new BException("hello you see") }
}
			
test "testMultipleMatchingCatchesWillOnlyExecuteTheFirstOne" {
	
	const a = new A()
			
	try {
		a.m1()
		assert.fail("Should have thrown exception")
	}	
				
	catch e : BException {
		// OK !
	}
			
	catch e : AException {
		assert.fail("incorrenct catch !")
	}
				
	catch e {
		assert.fail("incorrenct catch !")
	}
}