import wollok.lang.Exception

class BusinessException inherits Exception {
	constructor(_message) {message = _message}
}

test "Use throwsExceptionWithMessage" {
	try {
		assert.throwsExceptionWithMessage("hola!", { => throw new BusinessException("Jamaica") })
	}
	catch ex {
		/* OK */
	}
}